### PR TITLE
Update 2023-02-08.md

### PR DESCRIPTION
**Pull request by iamGeorgePro**
Add detail notes to Akash Network Content Moderation Working Group (wg) - Meeting #4

### CODE REVIEW

**Review by anilmurty — APPROVED** [review]

**Comment by anilmurty** [comment]
@brewsterdrinkwater - I just merged your notes. Are those the correct ones or these?

**Comment by anilmurty** [comment]
Actually - can you please merge whatever is the correct one @brewsterdrinkwater

**Comment by iamGeorgePro** [comment]
I am sure there is conflict because because it seems I  did the PR on the wrong [location](https://github.com/akash-network/community/blob/main/wg-content-moderation/README.md) on GitHub. This is the right [location](https://github.com/akash-network/community/pull/117) where the notes should be.

**Comment by anilmurty** [comment]
so what do you want to do here? close this and open new PR? @brewsterdrinkwater

**Pull request closed without merging**
