### PR TITLE
WIP Add service icons PRD

### PR DESCRIPTION
**Pull request by cloud-j-luna**
This PR adds the first version (1.0) of the "Service Icons" PRD.

TODO:

- [x] Showcase designs
- [ ] Add usage examples

### CODE REVIEW

**Comment by anilmurty** [comment]
Some comments/ questions:
1. Is this supposed to be an exhaustive list of all places where icons may be required, that we can think of at this time?
2. This talks about "services" but mixes "resources" in as well (like persistent storage)
3. Should the icons be client/ implementation neutral (for e.g - should it just there just be an icon for notifications, rather than cloudmos notifications)
4. The project overview section mentions this only being used in documentation. Does this not apply to the product(s) itself?  If yes, then this would mean having to redesign some existing products. If no, then this would mean having documentation be inconsistent with how the icons are being represented in the product. 

I guess overall I'm a little unclear on the goal and the need (urgency) to define a standard set of icons right now.

Separately, and assuming we do intend to do this: Are the icons noted here just examples or the actual icons being suggested. If the actual icons, then I'm not sure if these are the most representative of the specific feature/ service they are supposed to represent. For example: the icon for the deployment looks like a CPU (and would make more sense to use for indicating the CPU resource, rather than a deployment)

**Comment by cloud-j-luna** [comment]
> Some comments/ questions:
> 1. Is this supposed to be an exhaustive list of all places where icons may be required, that we can think of at this time?

No, this is a list and specification of the official icons for the services provided.

> 2. This talks about "services" but mixes "resources" in as well (like persistent storage)

Its supposed to represent services provided by the Akash Network ecosystem. I see Persistent Storage as a service (through a deployment, but still a service provided). Another example of a service would be a GPU Deployment. It's a point for further discussion and alignement.

> 3. Should the icons be client/ implementation neutral (for e.g - should it just there just be an icon for notifications, rather than cloudmos notifications)

We need to think of it as a Service, an abstraction on the underlying tech stack. With this being said, I do agree the service should be alerts, rather than cloudmos alerts. The names of the services are open for discussion.

> 4. The project overview section mentions this only being used in documentation. Does this not apply to the product(s) itself?  If yes, then this would mean having to redesign some existing products. If no, then this would mean having documentation be inconsistent with how the icons are being represented in the product. 

With a standard being adopted its expected to be applied by products, documentation and marketing. I'll make this clearer on the PRD.
This way I can be sure when I talk about the IP Leases service in docs, marketing & products, it is all referencing the same service rather than have different names for the same service. (IP Lease, Deployment IP, ...)

> I guess overall I'm a little unclear on the goal and the need (urgency) to define a standard set of icons right now.

This will be addressed on the usage section. But to give a brief overview, with the new open model communication should be standardized including these icons and the services they represent. These are also being used on our end on drawing tools, such as draw.io

> Separately, and assuming we do intend to do this: Are the icons noted here just examples or the actual icons being suggested. If the actual icons, then I'm not sure if these are the most representative of the specific feature/ service they are supposed to represent. For example: the icon for the deployment looks like a CPU (and would make more sense to use for indicating the CPU resource, rather than a deployment)

These are the icons being suggestes. The Deployments icon is a CPU with lines resembling a container. Of course this is all open for discussion and further change. If it would help we can start first by defining what are services and what are features.

**Comment by aktdenis** [comment]
Thanks cloud-j-luna! Couple of things from my side:

Are we talking about icons or pictograms... From my perspective icons represent a specific action. On the other hand, pictograms represent a concept and are usually richer in details. 

From our conversations and the website example i would say is the latter. I would like to avoid overlapping contributions for the same or similar thing, since Julius is already working on set of illustrations. (will be presented and discussed in our next sig-design meeting). 

This is a good starting point, but I would take a step back and provide a list of all services or products that need a representation in that form. And also provide mockups of where and why exactly are they used. (besides quasarch website - I'm thinking of Akash Network and the rest of the ecosystem)

We have a great challenge of creating a cohesive design experience for Akash. Which means consistency in appearance where ever user interacts with Akash and making sure all design elements are complementing each other. (typography, colors, illustrations, graphics, ui etc.) 

It's almost like putting a puzzle together, we got assets coming from different directions at the same time - but they gotta form a nice picture at the end. :)

Ty!

**Comment by anilmurty** [comment]
I feel like there are enough questions here that is worthy of a live discussion. Unless there is any opposition, I suggest we review this at one of the sig meetings. sig-design seems like the most appropriate venue @brewsterdrinkwater

**Pull request closed without merging**
