### PR TITLE
chore: add notes to sig-providers

### PR DESCRIPTION
**Pull request by figurestudios**
Signed-off-by: figurestudios <64747030+figurestudios@users.noreply.github.com>

https://github.com/akash-network/community/issues/50

### CODE REVIEW

**Comment by lechenghiskhan** [comment]
For the notes, please update the format to include the following subheaders and ensure only relevant items are nested with each one. @figurestudios (thank you!)
- Key Friction Points
- Potential Solutions
- Next Steps 
- Updates (if applicable)

**Comment by figurestudios** [comment]
Thanks @brewsterdrinkwater, will do.

**Comment by lechenghiskhan** [comment]
This looks good @figurestudios 
Thank you for making those edits!

**Comment by lechenghiskhan** [comment]
> @figurestudios it would be great if you could join sig-provider moving forward, and be the official note taker.

That would be amazing. @figurestudios please touch base with @brewsterdrinkwater and I for the note-taking bounty.

**Review by anilmurty — APPROVED** [review]

**Pull request merged**
